### ISSUE TITLE
English Lab Instructions

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/SC-900-Microsoft-Security-Compliance-and-Identity-Fundamentals#1]
Hi,

Where can I find lab instructions in English. Thanks

**Comment by ceperezb** [comment]
SC-900 currently does not have any labs. This repo was created as a placeholder.  If/when labs are available, updates will be made to the corresponding courseware in Skillpipe and communicated through the process with updates to Title Manager.  thanks!
