### ISSUE TITLE
LAB_07_explore_sentinel.md - unable to find Data connectors 

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/SC-900-Microsoft-Security-Compliance-and-Identity-Fundamentals#113]
# Module: 00
#### Step 03
Description of issue

I can't find Data connectors or configuration group in the Log analytics workspace.

So, I was unable to perform Task 4 as well.

![image](https://github.com/MicrosoftLearning/SC-900-Microsoft-Security-Compliance-and-Identity-Fundamentals/assets/98971092/98c86216-4ddb-4540-b365-16563339ea2c)

**Comment by sehrish777** [comment]
Hello There,
Can we please have an update here?

**Comment by ITBlandMCT** [comment]
There is a new version of this lab; this issue should be closed.
