### ISSUE TITLE
Issue in LAB_13_explore_senstivity_labels.md

### ISSUE THREAD

**Issue by bonzz** [MicrosoftLearning/SC-900-Microsoft-Security-Compliance-and-Identity-Fundamentals#18]
# Module: 04
#### Step: 09 - In the middle of the page, notice how there are three labels already created. Select Confidential - Finance. A window opens that provides information about this label. Note how this label is set to support both encryption and content marking. Select Edit Label at the top of the page to view some of the basic configuration settings.

Description of issue

We are not able to find three labels instead only two were shown as shown in the image and Confidential - finance is not available

![image](https://user-images.githubusercontent.com/48308835/125389188-70c23800-e3be-11eb-93a6-371440935141.png)

#### Step: 01 -From the Microsoft 365 compliance center home page, select the app launcher icon, next to where it says Contoso Electronics. right click on the Word icon and select Open in new tab.

Description of issue
Not able to understand this step, from where does one have to select the app launcher icon?
![image](https://user-images.githubusercontent.com/48308835/125388578-5dfb3380-e3bd-11eb-98ed-4aa0bfe418f0.png)

Can you please help us out.
Regards

**Comment by ceperezb** [comment]
hi Bonzz:  thank you for your comment, I have reviewed in the Microsoft 365 tenant that comes from an Authorized lab hoster (ALH) and that is specified for the SC900 labs and, it does show the sensitivity labels referenced in the lab step.  If you are using a different tenant you may see different information.

With regard to the 2nd item, regarding where to find the app launcher icon, see image below.   If you hover your mouse over the icon, you will also see that is says "app launcher".  

I will close this issue, but if you have other questions or are using M365 tenant for use with SC900, please let me know. thanks!

![app launcher and sensivity labels](https://user-images.githubusercontent.com/39444227/126684479-f31e0620-4bc7-46b3-a43e-4d0fe6fef32b.PNG)
