### ISSUE TITLE
Issue in LAB_11_explore_service_trust_portal.md

### ISSUE THREAD

**Issue by bonzz** [MicrosoftLearning/SC-900-Microsoft-Security-Compliance-and-Identity-Fundamentals#19]
# Module: 04
#### Step: 2 - In the address bar enter https://aks.ms/STP. 

Description of issue
The URL is not correct
![image](https://user-images.githubusercontent.com/48308835/125404294-18963080-e3d4-11eb-8f79-e970e5cf678c.png)

#### Step: 12 - From the top of the page, select Industries & Regions. Choose Regional Solutions. Notice the different Regions listed. Select United Kingdom.

Description of issue
No options are available to select under  **Industries & Regions** as shown in below video demo of the issue.

[Video demo](https://drive.google.com/file/d/12AQ6itmXoevANOr6BU6OTvRv50VXmrqu/view?usp=sharing)

Please take a look into this
Regards
Bony

**Comment by ceperezb** [comment]
Thanks for calling this out.  The URL has a typo which has since been updated.
