### ISSUE TITLE
Issue in LAB_05_explore_nsg.md

### ISSUE THREAD

**Issue by LuongNguyen0906** [MicrosoftLearning/SC-900-Microsoft-Security-Compliance-and-Identity-Fundamentals#20]
# Module: 00
#### Step: 00

Description of issue: Inconsistent in title

Repro steps:

The title of lab is inconsistent. 

Explore started with Azure Network Security Groups (NSGs)
&
Lab: Explore Azure Network Security Groups (NSGs).

**Comment by ceperezb** [comment]
thank you for calling this out.  The title has been updated.
