### ISSUE TITLE
Issue in LAB_08_explore_mcas.md

### ISSUE THREAD

**Issue by Ritu786** [MicrosoftLearning/SC-900-Microsoft-Security-Compliance-and-Identity-Fundamentals#21]
#### Step: 09

Description of issue: App connector is not available.

As per the Lab guide, there should be app connector in the setting cog icon but it is not available there which is effecting Task 2 and Task 3 as well.

![image](https://user-images.githubusercontent.com/65646433/125784782-10fd1454-f16d-44e3-ad47-6e120f65c76c.png)

**Comment by ceperezb** [comment]
hi Ritu786:  thank you for your comment.  I have re-checked the in Microsoft 365 tenant used for the SC900 labs (available through an authorized lab hoster) and app connector is shown, per the image below.  If you are using a different tenant you may see different information.  If you have other questions/issues please advise.  thanks!

![image](https://user-images.githubusercontent.com/39444227/126685870-2485e716-3192-4aa2-af5c-fdeefad61a1e.png)
