### ISSUE TITLE
Issue on DEMO_explore_sentinel.md

### ISSUE THREAD

**Issue by LuongNguyen0906** [MicrosoftLearning/SC-900-Microsoft-Security-Compliance-and-Identity-Fundamentals#24]
### Step: Demo part 4, step 4, point 4.

Description of issue

A sentence seems incomplete. 

Repro steps:

"Any automation rule you create on this page is triggered by the analytics rule you are c Note that you can add conditions and set actions for the rule."

**Comment by ceperezb** [comment]
LuongNguyen0906 - thank you for the feedback - good call out!!! I have updated the step. Thanks!!!
