### ISSUE TITLE
Unable to find my Unique Tenant ID 

### ISSUE THREAD

**Issue by BigTree98** [MicrosoftLearning/SC-900-Microsoft-Security-Compliance-and-Identity-Fundamentals#26]
# Module: 00
#### Step: 00

Description of issue

Unable to find my Unique Tenant ID and my Lab hosting provider does not have a copy of this either.

**Comment by ceperezb** [comment]
hi @BigTree98:  Please advise on which Authorized lab hoster you are using and include a screen shot the VM.  You should see a window on the right side of the screen that includes several tabs, including instructions and resources.  If you select the resources tab you will see the tenant information.   Refer to the screen shot below.

![image](https://user-images.githubusercontent.com/39444227/127886871-752f9160-aeab-4971-9e28-059e96d4c3dd.png)
