### ISSUE TITLE
Lab: Explore Azure Security Center Needs Review

### ISSUE THREAD

**Issue by StevenLODS** [MicrosoftLearning/SC-900-Microsoft-Security-Compliance-and-Identity-Fundamentals#31]
# Module: 03
#### Step: All
Description of issue

Lab: Explore Azure Security Center needs to be reviewed as it looks like most steps don't align with an Azure Pass subscription. Not sure if there has been UI changes which has moved some of the features mentioned, but as of right now attempting to go through these steps have been confusing. Let me know if I can provide any further information.

**Comment by ceperezb** [comment]
hi Steven:  yes content has recently changed in Azure Security Center and will be updated by early December. Will follow up iwth any quesitons.  Thanks!!!
