### ISSUE TITLE
LAB_11_explore_service_trust_portal.md

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/SC-900-Microsoft-Security-Compliance-and-Identity-Fundamentals#71]
# Module: 00
#### Step: 05

Description of issue
There are no longer a specifically-labelled set of "six key privacy principles" on the page in this step.

Probably need to rewrite that step to reference other privacy resources that are available on that page now, or possibly you can find where the 6 key principles live now - I couldn't find them.

**Comment by ceperezb** [comment]
Thank you Test Tersterson1004 for your comments. The lab and demo have been updated.  Although the six principles are not explicitly listed on these pages, the text covered throughout various links speaks to the principles.  Thanks!!
