### ISSUE TITLE
LAB_05_explore_nsg: Cannot RDP to VM

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/SC-900-Microsoft-Security-Compliance-and-Identity-Fundamentals#85]
# Module: 03
#### Step: 21

Description of issue

The steps seem to assume we are going to be able to successfully connect via RDP, however...this doesn't succeed.  

I am uncertain how it is expected to succeed in any case...as the previous steps have specifically disabled the port 3389 inbound access + the NSG config.

If this anomaly is caused by recent Azure changes in default behavior, recommend either excising the steps from 16-21 altogether, or perhaps (if connecting to VM is desired task) replace them with new steps to create a Bastion connection to the VM.

**Comment by ceperezb** [comment]
thank you for calling this out. updates have been made.
